### PR TITLE
Post: JRuby and Exception Handling Performance

### PR DESCRIPTION
**Pull request by chuckremes**
Short blog post detailing a recent project that highlighted a JRuby exception handling performance bug.

### CODE REVIEW

**Comment by headius** [comment]
Thanks for the post, @chuckremes!

A few comments and suggestions:

* You mention talking about the problems and "their ultimate solution" but the article stops short of doing that. All the fixes we promised were on master within a couple days, and the JVM flags are no longer needed to run stock csv.rb correctly. We'd like to see that mentioned, and the final results should be the results against master (which will become 9.0.2).
* Your previous post showed single-threaded results of MRI versus RBX. This one only shows the multithreaded performance. I think it would be nice to show all three single-threaded again (post fix only, probably, since pre-fix there's not much to show.
* If comparing all three starts to seem too cumbersome, perhaps we could just drop RBX, or only include MRI in the single-threaded results (since it's exactly the same perf for multi-threaded).

Thanks a bunch for working with us to find these issues. We're very excited that we could fix them in such a short time!

**Comment by headius** [comment]
Ping @chuckremes...still interested in getting this post up?

**Comment by chuckremes** [comment]
Sure. Is it ready to post or do you want changes?

**Comment by headius** [comment]
@chuckremes Did you get my comments above? I think just a few minor changes are needed, to emphasize JRuby's single-thread perf being the best and point out that the next release has all the fixes we worked on (ideally by showing the numbers against an actual JRuby build with no special flags).

**Comment by headius** [comment]
I just posted an entry about the performance improvements we made. We'd still like to have your post detailing how much better your application works (and how it is once again fastest on JRuby) but there's less pressure now :-)

**Comment by chuckremes** [comment]
I submitted a PR a few weeks ago. Want me to update it to point to your new post about the improvements? If not, the post is ready to go. Just merge the PR.

**Comment by headius** [comment]
@chuckremes I had some suggestions for updates here: https://github.com/jruby/blog.jruby.org/pull/10#issuecomment-145075253

Mostly I'd just like to see it demonstrating the *released* perf improvements (since the JVM flag is no longer required) and showing JRuby as fastest in both single-threaded and multi-threaded cases.

**Pull request closed without merging**
